added ts, tsx, jsx support
SamVerschueren/vscode-ava pull request #5
Opened 2017-07-18 18:55 UTC by everdrone

- Added support for typescript, typescript react and javascript react.  
- Fixed closing bracket on `test.failing` snippet

2017-07-24 11:15 UTC, SamVerschueren requested changes

2017-07-24 11:15 UTC, SamVerschueren commented on package.json
> +	"name": "ava",
Do not change indentation

2017-07-24 11:15 UTC, SamVerschueren commented on package.json
> +	"__metadata": {
Remove metadata

2017-07-24 11:15 UTC, SamVerschueren commented on package.json
> +}
Add final newline

2018-06-14 16:25 UTC, antonvasin commented
Hi. I can jump in and finish this PR if still relevant

2018-06-14 20:52 UTC, everdrone commented
Hi all, totally forgot about this, sorry for the inconvenience.
closing.

2018-06-14 20:52 UTC, closed without merging